config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes, only: [:index, :new, :create, :destroy]
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  resources :quests
  get "signup" => 'users#new'
  get "login" => 'sessions#new'
  get "logout" => 'sessions#destroy'
  get "questcalendar" => 'quests#index'
  
  get '/auth/:provider/callback', to: 'authentications#create'
  
  resources :users
  resources :sessions
  resources :groups do
    resources :posts
  end
  
  # get groups/2/posts
  
  root to: 'home#index'
  get "about" => 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/quest.rb
class Quest < ApplicationRecord
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :set_quest, only: [:show, :edit, :update, :destroy]

  # GET /quests
  # GET /quests.json
  def index
    @quests = Quest.all
  end

  # GET /quests/1
  # GET /quests/1.json
  def show
  end

  # GET /quests/new
  def new
    @quest = Quest.new
  end

  # GET /quests/1/edit
  def edit
  end

  # POST /quests
  # POST /quests.json
  def create
    @quest = Quest.new(quest_params)

    respond_to do |format|
      if @quest.save
        format.html { redirect_to @quest, notice: 'Quest was successfully created.' }
        format.json { render :show, status: :created, location: @quest }
      else
        format.html { render :new }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quests/1
  # PATCH/PUT /quests/1.json
  def update
    respond_to do |format|
      if @quest.update(quest_params)
        format.html { redirect_to @quest, notice: 'Quest was successfully updated.' }
        format.json { render :show, status: :ok, location: @quest }
      else
        format.html { render :edit }
        format.json { render json: @quest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quests/1
  # DELETE /quests/1.json
  def destroy
    @quest.destroy
    respond_to do |format|
      format.html { redirect_to quests_url, notice: 'Quest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quest
      @quest = Quest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quest_params
      params.require(:quest).permit(:name, :start_time)
    end
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/quests/_form.html.erb
<%= form_with(model: quest, local: true) do |form| %>
  <% if quest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quest.errors.count, "error") %> prohibited this quest from being saved:</h2>

      <ul>
        <% quest.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quests/edit.html.erb
<h1>Editing Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Show', @quest %> |
<%= link_to 'Back', quests_path %>

app/views/quests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quests</h1>

<!--
<table class="questTable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quests.each do |quest| %>
      <tr>
        <td><%= quest.name %></td>
        <td><%= quest.start_time %></td>
        <td><%= link_to 'Show', quest %></td>
        <td><%= link_to 'Edit', edit_quest_path(quest) %></td>
        <td><%= link_to 'Destroy', quest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>
<div class="container-events">
  <%= month_calendar(events: @quests) do |date, quests| %>
    <%= date.day %>
  
    <% quests.each do |quest| %>
      <div>
        <%= link_to_unless_current quest.name, quest %>
      </div>
    <% end %>
  <% end %>
  <%= link_to 'New Quest', new_quest_path %>
</div>

app/views/quests/new.html.erb
<h1>New Quest</h1>

<%= render 'form', quest: @quest %>

<%= link_to 'Back', quests_path %>

app/views/quests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quest.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @quest.start_time %>
</p>

<%= link_to 'Edit', edit_quest_path(@quest) %> |
<%= link_to 'Back', quests_path %> |
<%= link_to 'Destroy', @quest, method: :delete, data: { confirm: 'Are you sure?' } %>