config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes, only: [:index, :new, :create, :destroy]
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  resources :quests
  get "signup" => 'users#new'
  get "login" => 'sessions#new'
  get "logout" => 'sessions#destroy'
  get "questcalendar" => 'quests#index'
  
  get '/auth/:provider/callback', to: 'authentications#create'
  
  resources :users
  resources :sessions
  resources :groups do
    resources :posts
  end
  
  # get groups/2/posts
  
  root to: 'home#index'
  get "about" => 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :posts
    belongs_to :user
    
    validates :name, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate
  
  #loading group for these methods
  before_action :load_group, except: [:index, :new, :create]
  
  #Shows all instances
  def index
    @groups = current_user.groups
  end
  
  #Redirect to a from creation of a group instance 
  def new
    @group = Group.new
  end
  
  #Creating an instance
  def create
    @group = Group.new group_params
    @group.user = current_user
    if @group.save
      redirect_to groups_path, notice: "Group created!"
    else
      render :new
    end
  end
  
  ###The instance will be loaded first before calling these methods
  #Show an instance
  def show
    @post = Post.new
  end
  
  #Edit an instance
  def edit
  end
  
  #Update an instance
  def update
    if @group.update group_params
      redirect_to @group, notice: "Group updated!"
    else
      render :edit
    end
  end
  
  #Delete an instance
  def destroy
    @group.destroy
    redirect_to groups_path, alert: "Group deleted!"
  end
  
  private
  
  def load_group
    @group = current_user.groups.find params[:id]
  end
  
  def group_params
    params.require(:group).permit(:name,:description,:image_url)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_with(model: @group, local: true, layout: :horizontal,
                        label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
    <%= f.alert_message "Please fix the errors below.", error_summary: false %>
    <%= f.text_field :name %>
    <%= f.text_field :description %>
    <%= f.text_field :image_url %>
    <%= f.form_group do %>
        <%= f.primary @group.persisted? ? "Update Group" :"Create Group" %>
    <% end %>
<% end %>

app/views/groups/_group.html.erb
<div id="group_<%= group.id %>" class="group">
    <div class="group_pic">
        <img src="<%= group.image_url %>" alt="<%= group.name %> picture">
    </div>
    <p><strong><span class="blacking">Name:</span> </strong><span class="enlarging"><%= link_to_unless_current group.name, group %></span></p>
    <p><strong><span class="blacking">Description:</span> </strong><%= group.description %></p>
    
</div>

app/views/groups/edit.html.erb
<% title "Edit Group" %>

<%= render 'form' %>

<%= link_to "Cancel", groups_path, class: "btn btn-secondary" %>

app/views/groups/index.html.erb
<% title "Groups" %>

<%= render @groups %>

<%= link_to "New Group", new_group_path, class: "btn btn-primary" %>

app/views/groups/new.html.erb
<% title "New Group" %>

<%= render 'form' %>

<%= link_to "Cancel", groups_path, class: "btn btn-secondary" %>

app/views/groups/show.html.erb
<% title "Group" %>

<%= render @group %>

<%= link_to "Edit", edit_group_path(@group) %> |
<%= link_to "Delete", @group, method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to "All Groups", groups_path %>

<h3>Posts:</h3>

<%= render @group.posts %>
<%= link_to "New Post", new_group_post_path(@group), class: "btn btn-primary" %>