config/routes.rb
Rails.application.routes.draw do
  
  resources :resumes, only: [:index, :new, :create, :destroy]
  get 'resumes/index'
  get 'resumes/new'
  get 'resumes/create'
  get 'resumes/destroy'
  resources :quests
  get "signup" => 'users#new'
  get "login" => 'sessions#new'
  get "logout" => 'sessions#destroy'
  get "questcalendar" => 'quests#index'
  
  get '/auth/:provider/callback', to: 'authentications#create'
  
  resources :users
  resources :sessions
  resources :groups do
    resources :posts
  end
  
  # get groups/2/posts
  
  root to: 'home#index'
  get "about" => 'home#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :group
    
    validates :title, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate
  before_action :load_group
  before_action :load_post, except: [:index, :new, :create]
  
  def index
    @posts = @group.posts
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new post_params
    if @group.posts << @post
      redirect_to group_path(@group), notice: "Post created!"
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update post_params
      redirect_to [@group,@post], notice: "Post updated!"
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    redirect_to group_posts_path(@group)
  end
  
  private
  
  def load_group
    @group = current_user.groups.find params[:group_id] # /group/10/posts
  end
  
  def load_post
    @post = @group.posts.find params[:id]
  end
  
  def post_params
    params.require(:post).permit(:title,:detail,:rarity)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= bootstrap_form_with(model: [@group, @post], local: true, layout: :horizontal,
                        label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
    <%= f.alert_message "Please fix the errors below.", error_summary: false %>
    <%= f.text_field :title %>
    <%= f.text_field :detail %>
    <%= f.number_field :rarity %>
    <%= f.form_group do %>
        <%= f.primary @post.persisted? ? "Update Post" : "Create Post" %>
    <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="post_<%= post.id %>" class="post">
    <p><strong><span class="blacking">Title:</span></strong> <span class="postTitle"><%= link_to_unless_current post.title, group_post_path(@group,post) %></span></p>
    <p><strong>Detail:</strong> <%= post.detail %></p>
    <p><strong><span class="rare">Rarity:</span> </strong> <%= post.rarity %></p>
</div>

app/views/posts/edit.html.erb
<% title "Edit Post" %>

<%= render 'form' %>

<%= link_to "Cancel", [@group,@post], class: "btn btn-secondary" %>

app/views/posts/index.html.erb
<% title @group.name %>
<h1>Posts:</h1>

<%= render @posts %>

<%= link_to "All Groups", groups_path %></br>
<%= link_to "New Post", new_group_post_path(@group,@post), class: "btn btn-primary" %>
 <!-- /posts/10/posts/new --!>

app/views/posts/new.html.erb
<% title "New Post" %>

<%= render 'form' %>

<%=link_to "Cancel", group_path(@group), class: "btn btn-secondary" %>

app/views/posts/show.html.erb
<% title @post.title %>

<%= render @post %>

<%= link_to "Edit", edit_group_post_path(@group,@post) %> |
<%= link_to "Delete", group_post_path(@group,@post), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to "All Posts", group_posts_path(@group) %>